/**********************************************************
filename   : common_motors.h
function   : 普通电机
author     : 谢令
created    : 2022-12-05
comment    :
**********************************************************/
#ifndef _WORKER_COMMON_MOTORS_H_
#define _WORKER_COMMON_MOTORS_H_

#include "public_common_motors_extern.h"

/*
* 本单元通用电机标识（对象）定义
*/
enum COMMON_MOTORS_IDS
{
    COMMON_MOTOR_CLEAN_PLATE_ROTATE,          // 
    COMMON_MOTOR_CLEANER_SUCKER_VERT,         // 
    COMMON_MOTOR_SUBSTRATE_MIXER_VERT,        // 
    COMMON_MOTOR_SUBSTRATE_A_PLUNGER,         // 
    COMMON_MOTOR_SUBSTRATE_B_PLUNGER,         // 
    COMMON_MOTOR_CLEANER_MIXER_VERT,          // 
    COMMON_MOTORS_NUMBER                      // = 6
};

// 吸、吐 对应的电机方向定义
#define SUCK  FORWARD
#define SPIT  BACKWARD

// 动作步骤分解ID
enum MOTOR_MOTION_IDS{
    MOTION_CLEAN_PLATE_ROTATE_INIT_SETP0,     // 旋转电机
    MOTION_CLEAN_PLATE_ROTATE_INIT_SETP1,     // 
    MOTION_CLEAN_PLATE_ROTATE_TO_X_SETP0,     // 
    MOTION_CLEAN_PLATE_ROTATE_TO_X_SETP1,     // 
    MOTION_CLEAN_PLATE_ROTATE_TO_0_SETP0,     // 
    MOTION_CLEAN_PLATE_ROTATE_TO_0_SETP1,     // 
    MOTION_CLEANER_SUCKER_VERT_INIT_SETP0,    // 升降电机
    MOTION_CLEANER_SUCKER_VERT_INIT_SETP1,    // 
    MOTION_CLEANER_SUCKER_VERT_TO_X_SETP0,    // 
    MOTION_CLEANER_SUCKER_VERT_TO_X_SETP1,    // 
    MOTION_CLEANER_SUCKER_VERT_TO_0_SETP0,    // 
    MOTION_CLEANER_SUCKER_VERT_TO_0_SETP1,    // 
    MOTION_SUBSTRATE_MIXER_VERT_INIT_SETP0,   // 混匀升降电机
    MOTION_SUBSTRATE_MIXER_VERT_INIT_SETP1,   // 
    MOTION_SUBSTRATE_MIXER_VERT_TO_X_SETP0,   // 
    MOTION_SUBSTRATE_MIXER_VERT_TO_X_SETP1,   // 
    MOTION_SUBSTRATE_MIXER_VERT_TO_0_SETP0,   // 
    MOTION_SUBSTRATE_MIXER_VERT_TO_0_SETP1,   // 
    MOTION_SUBSTRATE_A_PLUNGER_INIT_SETP0,    // 柱塞泵电机
    MOTION_SUBSTRATE_A_PLUNGER_INIT_SETP1,    // 
    MOTION_SUBSTRATE_A_PLUNGER_TO_X_SETP0,    // 
    MOTION_SUBSTRATE_A_PLUNGER_TO_X_SETP1,    // 
    MOTION_SUBSTRATE_A_PLUNGER_TO_0_SETP0,    // 
    MOTION_SUBSTRATE_A_PLUNGER_TO_0_SETP1,    // 
    MOTION_SUBSTRATE_B_PLUNGER_INIT_SETP0,    // 柱塞泵电机
    MOTION_SUBSTRATE_B_PLUNGER_INIT_SETP1,    // 
    MOTION_SUBSTRATE_B_PLUNGER_TO_X_SETP0,    // 
    MOTION_SUBSTRATE_B_PLUNGER_TO_X_SETP1,    // 
    MOTION_SUBSTRATE_B_PLUNGER_TO_0_SETP0,    // 
    MOTION_SUBSTRATE_B_PLUNGER_TO_0_SETP1,    // 
    MOTION_CLEANER_MIXER_VERT_INIT_SETP0,     // 混匀升降电机
    MOTION_CLEANER_MIXER_VERT_INIT_SETP1,     // 
    MOTION_CLEANER_MIXER_VERT_TO_X_SETP0,     // 
    MOTION_CLEANER_MIXER_VERT_TO_X_SETP1,     // 
    MOTION_CLEANER_MIXER_VERT_TO_0_SETP0,     // 
    MOTION_CLEANER_MIXER_VERT_TO_0_SETP1,     // 
    MOTIONS_NUMBER
};

/*
* 本单元普通电机动作标识（对象）定义
*/
enum MOTOR_ACTIONS_IDS{
    MOVE_ACT_CLEAN_PLATE_ROTATE_INIT,         // 旋转电机
    MOVE_ACT_CLEAN_PLATE_ROTATE_TO_X,         // 
    MOVE_ACT_CLEAN_PLATE_ROTATE_TO_0,         // 
    MOVE_ACT_CLEANER_SUCKER_VERT_INIT,        // 升降电机
    MOVE_ACT_CLEANER_SUCKER_VERT_TO_X,        // 
    MOVE_ACT_CLEANER_SUCKER_VERT_TO_0,        // 
    MOVE_ACT_SUBSTRATE_MIXER_VERT_INIT,       // 混匀升降电机
    MOVE_ACT_SUBSTRATE_MIXER_VERT_TO_X,       // 
    MOVE_ACT_SUBSTRATE_MIXER_VERT_TO_0,       // 
    MOVE_ACT_SUBSTRATE_A_PLUNGER_INIT,        // 柱塞泵电机
    MOVE_ACT_SUBSTRATE_A_PLUNGER_TO_X,        // 
    MOVE_ACT_SUBSTRATE_A_PLUNGER_TO_0,        // 
    MOVE_ACT_SUBSTRATE_B_PLUNGER_INIT,        // 柱塞泵电机
    MOVE_ACT_SUBSTRATE_B_PLUNGER_TO_X,        // 
    MOVE_ACT_SUBSTRATE_B_PLUNGER_TO_0,        // 
    MOVE_ACT_CLEANER_MIXER_VERT_INIT,         // 混匀升降电机
    MOVE_ACT_CLEANER_MIXER_VERT_TO_X,         // 
    MOVE_ACT_CLEANER_MIXER_VERT_TO_0,         // 
    MOTOR_ACTIONS_NUMBER 
};

#endif
